server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

jwt:
  secret: ithscomplexjavaithscomplexjavaithscomplexjavaithscomplexjavaithscomplexjavaithscomplexjavaithscomplexjava

logging:
  level:
    root: WARN
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat:
                TomcatWebServer: INFO

auktionera:
  rabbitmq:
    exchange: auktionera.exchange
    queue: auktionera.queue
    routing-key: auktionera.routingkey


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/auktionera?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: petros
    password: root

  main:
    banner-mode: off
    allow-bean-definition-overriding: true




